/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsNewRouteImport } from './routes/topics.new'
import { Route as TopicsTopicIdIndexRouteImport } from './routes/topics.$topicId.index'
import { Route as TopicsTopicIdResultsRouteImport } from './routes/topics.$topicId.results'
import { Route as TopicsTopicIdSettingsRouteImport } from './routes/topics.$topicId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopicsRoute,
} as any)
const TopicsNewRoute = TopicsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TopicsRoute,
} as any)
const TopicsTopicIdIndexRoute = TopicsTopicIdIndexRouteImport.update({
  id: '/$topicId/',
  path: '/$topicId/',
  getParentRoute: () => TopicsRoute,
} as any)
const TopicsTopicIdResultsRoute = TopicsTopicIdResultsRouteImport.update({
  id: '/$topicId/results',
  path: '/$topicId/results',
  getParentRoute: () => TopicsRoute,
} as any)
const TopicsTopicIdSettingsRoute = TopicsTopicIdSettingsRouteImport.update({
  id: '/$topicId/settings',
  path: '/$topicId/settings',
  getParentRoute: () => TopicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/topics': typeof TopicsRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/topics/new': typeof TopicsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicId/results': typeof TopicsTopicIdResultsRoute
  '/topics/$topicId/settings': typeof TopicsTopicIdSettingsRoute
  '/topics/$topicId/': typeof TopicsTopicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/topics/new': typeof TopicsNewRoute
  '/admin': typeof AdminIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/topics/$topicId/results': typeof TopicsTopicIdResultsRoute
  '/topics/$topicId/settings': typeof TopicsTopicIdSettingsRoute
  '/topics/$topicId': typeof TopicsTopicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/topics': typeof TopicsRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/topics/new': typeof TopicsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicId/results': typeof TopicsTopicIdResultsRoute
  '/topics/$topicId/settings': typeof TopicsTopicIdSettingsRoute
  '/topics/$topicId/': typeof TopicsTopicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/topics'
    | '/admin/categories'
    | '/admin/settings'
    | '/admin/users'
    | '/topics/new'
    | '/admin/'
    | '/topics/'
    | '/topics/$topicId/results'
    | '/topics/$topicId/settings'
    | '/topics/$topicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/admin/categories'
    | '/admin/settings'
    | '/admin/users'
    | '/topics/new'
    | '/admin'
    | '/topics'
    | '/topics/$topicId/results'
    | '/topics/$topicId/settings'
    | '/topics/$topicId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/topics'
    | '/admin/categories'
    | '/admin/settings'
    | '/admin/users'
    | '/topics/new'
    | '/admin/'
    | '/topics/'
    | '/topics/$topicId/results'
    | '/topics/$topicId/settings'
    | '/topics/$topicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/topics/new': {
      id: '/topics/new'
      path: '/new'
      fullPath: '/topics/new'
      preLoaderRoute: typeof TopicsNewRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/topics/$topicId/': {
      id: '/topics/$topicId/'
      path: '/$topicId'
      fullPath: '/topics/$topicId/'
      preLoaderRoute: typeof TopicsTopicIdIndexRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/topics/$topicId/results': {
      id: '/topics/$topicId/results'
      path: '/$topicId/results'
      fullPath: '/topics/$topicId/results'
      preLoaderRoute: typeof TopicsTopicIdResultsRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/topics/$topicId/settings': {
      id: '/topics/$topicId/settings'
      path: '/$topicId/settings'
      fullPath: '/topics/$topicId/settings'
      preLoaderRoute: typeof TopicsTopicIdSettingsRouteImport
      parentRoute: typeof TopicsRoute
    }
  }
}

interface TopicsRouteChildren {
  TopicsNewRoute: typeof TopicsNewRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  TopicsTopicIdResultsRoute: typeof TopicsTopicIdResultsRoute
  TopicsTopicIdSettingsRoute: typeof TopicsTopicIdSettingsRoute
  TopicsTopicIdIndexRoute: typeof TopicsTopicIdIndexRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsNewRoute: TopicsNewRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  TopicsTopicIdResultsRoute: TopicsTopicIdResultsRoute,
  TopicsTopicIdSettingsRoute: TopicsTopicIdSettingsRoute,
  TopicsTopicIdIndexRoute: TopicsTopicIdIndexRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  TopicsRoute: TopicsRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
