apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-polis.fullname" . }}
  labels:
    {{- include "private-polis.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.application.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "private-polis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: application
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.application.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "private-polis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: application
        {{- with .Values.application.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "private-polis.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: application
          image: "{{ .Values.application.image.repository }}:{{ include "private-polis.imageTag" (dict "tag" .Values.application.image.tag "Chart" .Chart) }}"
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "private-polis.fullname" . }}
            - secretRef:
                name: {{ include "private-polis.secretName" . }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
