{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "private-polis.serviceAccountName" . }}
  labels:
    {{- include "private-polis.labels" . | nindent 4 }}
  annotations:
    {{- with omit .Values.serviceAccount.annotations "argocd.argoproj.io/sync-wave" }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    argocd.argoproj.io/sync-wave: "-10"
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
