apiVersion: v2
name: private-polis
description: Private-first, self-hosted consensus platform
type: application
version: 0.4.0 # x-release-please-version
appVersion: "0.4.0" # x-release-please-version
home: https://github.com/UniPro-tech/awai
sources:
  - https://github.com/UniPro-tech/awai
keywords:
  - consensus
  - polis
  - privacy
annotations:
  artifacthub.io/license: Apache-2.0
  org.opencontainers.image.source: https://github.com/UniPro-tech/awai
